#!/bin/bash
source setup/environment


if [ ! -f "./env" ]; then
    echo "Env File does not exist. Name enviorment name."
    read env_name
    if [ ! -f "./envs/$env_name" ]; then
        echo "No pre configured environment found. Create new config and run again"
        exit 1
    else
        cp "./envs/$env_name" ./env
    fi
fi

readEnv type "TYPE"
readEnv newHostname "HOSTNAME"
if [ "$type" == "ubuntu" ]; then
  . setup/ubuntu
  install
fi

pushd $HOME
    if [ ! -d "~/.oh-my-zsh" ]; then
        echo "Installing zsh"
        sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" &
    fi

    brew > /dev/null 2> /dev/null
    if [ "$?" != "1" ]; then
        echo "Installing brew"
        bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    fi
popd

echo "Copying zshrc"
cp $HOME/env/.zshrc $HOME/


if [ "$type" == "macOS" ]; then
    . setup/brew
    . setup/asdf

    readEnv bundles "BUNDLES"
    readEnv asdf "ASDF"
    readEnv asdfversion "ASDF-VERSION"
    readEnv lockmsg "LOCKMESSAGE"
    readEnv code "CODE"
    
    for bundle in $bundles; do
        echo "";
        installBundle $bundle
    done

    for lang in $asdf; do
        lang $lang
        echo ""
    done

    asdfarr=($asdfversion)
    for (( i=0; i<${#asdfarr[@]} ; i+=2 )) ; do
        langVersion "${asdfarr[i]}" "${asdfarr[i+1]}"
    done

    for c in $code; do
        code --install-extension $c
    done

    
    . setup/mac
    installHackFont
    defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "~/env/mac/iterm" 
    setSaneDefaults
    setupDock
    setupLoginItems
    sudo scutil --set HostName ${newHostname}
    sudo defaults write /Library/Preferences/com.apple.loginwindow LoginwindowText "${lockmsg}"

fi

if [ "$type" == "ubuntu" ]; then
    . setup/brew
    
    . setup/asdf

    readEnv bundles "BUNDLES"
    readEnv asdf "ASDF"
    readEnv asdfversion "ASDF-VERSION"
    
    for bundle in $bundles; do
        echo "";
        installBundle $bundle
    done

    for lang in $asdf; do
        lang $lang
        echo ""
    done

    asdfarr=( $asdfversion )
    for (( i=0; i<${#asdfarr[@]} ; i+=2 )) ; do
        langVersion "${asdfarr[i]}" "${asdfarr[i+1]}"
    done

fi





# enable firewall, i nstall little snitch
#sudo defaults write /Library/Preferences/com.apple.alf globalstate -int 1
#sudo launchctl load /System/Library/LaunchDaemons/com.apple.alf.agent.plist 2>/dev/null